name: Build&Push Docker image to registry

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata (tags, labels) for the Docker image
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          DB_HOST=${{ vars.DB_HOST }}
          TOURNAMENT_DB_USER=${{ secrets.TOURNAMENT_DB_USER }}
          TOURNAMENT_DB_PASSWORD=${{ secrets.TOURNAMENT_DB_PASSWORD }}
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 2.59.80.141
          username: Kirill
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker stop tournament || true
            sudo docker rm tournament || true
            docker pull ghcr.io/rizm-151207/tournamentbracket.backend:master
            docker run --name tournament -d -p 8080:8080 --restart always ghcr.io/rizm-151207/tournamentbracket.backend:master --migrate
            echo "Deployment successful!"
