name: Build&Push Docker image to registry

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata (tags, labels) for the Docker image
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          TOURNAMENT_DB_USER=${{ secrets.TOURNAMENT_DB_USER }}
          TOURNAMENT_DB_PASSWORD=${{ secrets.TOURNAMENT_DB_PASSWORD }}
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH into VM and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key Kirill@2.59.80.141 &lt;&lt; 'EOF'
            sudo docker stop test || true
            sudo docker rm test || true
            docker pull ghcr.io/rizm-151207/tournamentbracket.backend:master
            docker run -p 80:8080 ghcr.io/rizm-151207/tournamentbracket.backend:master --name test --migrate
          EOF
